version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "banner_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    command: sh -c "sleep 1 && ./app"
    environment:
      - DATABASE_URL=postgres://postgres:12345678@postgres:5432/banner_app&sslmode=disable
      - REDIS_URL=redis://redis:6379

volumes:
  postgres-data:
